export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';
export const OPEN_ADMIN_MODAL = 'OPEN_ADMIN_MODEL';
